name: Pylint

on:
  push:
    paths:
      - "**.py"

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      - name: Analyse the code with pylint
        run: |
          # List all Python files tracked by git, excluding venv folders
          files=$(git ls-files '*.py' | grep -vE '(^venv/|^.venv/|^env/|^.env/)')
          if [ -n "$files" ]; then
            pylint $files
          else
            echo "No Python files found to lint."
          fi
