name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      - name: Analyse the code with pylint
        run: |
          # List all Python files tracked by git, excluding venv folders
          files=$(git ls-files '*.py' | grep -vE '(^venv/|^.venv/|^env/|^.env/)')
          if [ -n "$files" ]; then
            pylint $files
          else
            echo "No Python files found to lint."
          fi
